development:
  adapter: postgresql
  database: case2_development
  pool: 5
  timeout: 5000
  username: postgres
  password: adminuser

test:
  adapter: postgresql
  database: case2_test
  pool: 5
  timeout: 5000
  username: postgres
  password: adminuser

production:
  adapter: postgresql
  database: case2_production
  pool: 5
  timeout: 5000
  username: postgres
  password: admin
