development:
  adapter: postgresql
  database: case2_development
  pool: 5
  timeout: 5000
  username: reynan
  password: admin2016

test:
  adapter: postgresql
  database: case2_test
  pool: 5
  timeout: 5000
  username: reynan
  password: admin2016

production:
  adapter: postgresql
  database: case2_production
  pool: 5
  timeout: 5000
  username: postgres
  password: admin
