Client.create(name: 'A LITTLE MONEY PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'A LITTLE WORLD', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AB GEVECO SIGURD WALLDALL', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABAT, ZENAIDA C. MRS.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABCC ENVIRONMENTAL TECHNOLOGIES', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABN AMRO  BANK, INC.  (NOW ROYAL BANK OF SCOTLAND)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABOITIZ, LUIS MIGUEL MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABOITIZ, MA. REGINA AFRICA', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABRAC RESOURCES CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACACIO, ALBERT, MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACM LAND HOLDINGS, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACOSTA, ROWELA C. (REFERRED BY U.S. EMBASSY)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACOTEX INDUSTRIES CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACTIVE GROUP, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACTIVE REALTY  & DEVELOPMENT CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADAMSON AND ADAMSON INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADAMS, MICHAEL MR. (MAA CONSULTANTS, INC.)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADANIEL, EPPIE', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADELFA PROPERTIES & SENATE PRESIDENT MANUEL B. VILLAR', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADIDAS PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADRISTE PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADVANCE RECOVERY SYSTEM, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADVERTISING BOARD OF THE PHILIPPINES', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AFRICA, ROSARIO MRS.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AGHITECH PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AGRI-REALTY COMPANY., INC. (FORMERLY PURIPHIL REALTY DEVELOPMENT, INC.)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AGROTEX COMMODITIES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AIG AVIATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AIR FRANCE', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AIR FRANCE CARGO', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AJMR PORT SERVICES CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AL AWAN SAMEER MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ALANANO, ARNNIE MR', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ALBA, MARK MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')


Lawyer.create(first_name: 'JOSE', last_name: 'FLORES', middle_name: 'PACIS', position: 'PARTNER', email: 'jpflores@platonmartinez.com', rate: '', initials: 'JPF')
Lawyer.create(first_name: 'SAKLOLO', last_name: 'LEANO', middle_name: 'ALLOGUINES', position: 'PARTNER', email: 'saleano@platonmartinez.com', rate: '', initials: 'SAL')
Lawyer.create(first_name: 'AUGUSTO', last_name: 'SAN PEDRO', middle_name: 'SANTOS', position: 'PARTNER', email: 'asanpedro@platonmartinez.com', rate: '', initials: 'ASP')
Lawyer.create(first_name: 'CARLOS', last_name: 'PLATON', middle_name: 'GUTIERREZ', position: 'PARTNER', email: 'cgplaton@platonmartinez.com', rate: '', initials: 'CGP')
Lawyer.create(first_name: 'HECTOR', last_name: 'MARTINEZ', middle_name: 'AGUILA', position: 'PARTNER', email: 'hamartinez@platonmartinez.com', rate: '', initials: 'HAM')
Lawyer.create(first_name: 'ENNESTINE', last_name: 'FERNANDO', middle_name: 'VILLAREAL', position: 'PARTNER', email: 'edvfernando@platonmartinez.com', rate: '', initials: 'EDVF')
Lawyer.create(first_name: 'GRACE', last_name: 'PANAGSAGAN', middle_name: 'PADILLA', position: 'PARTNER', email: 'gpqpanagsagan@platonmartinez.com', rate: '', initials: 'GPQP')
Lawyer.create(first_name: 'OVALITO PETER', last_name: 'BANTILAN', middle_name: 'MANDAC', position: 'PARTNER', email: 'pmbantilan@platonmartinez.com', rate: '', initials: 'PMB')
Lawyer.create(first_name: 'ANTHONY BRETT', last_name: 'ABENIR', middle_name: 'MANDE', position: 'JUNIOR PARTNER', email: 'abmabenir@platonmartinez.com', rate: '', initials: 'ABMA')
Lawyer.create(first_name: 'JORGE AMBROSIO', last_name: 'ABES', middle_name: 'P', position: '', email: '', rate: '', initials: 'JAPA')
Lawyer.create(first_name: 'RYAN', last_name: 'ANDRES', middle_name: 'DEL PRADO', position: 'JUNIOR ASSOCIATE', email: 'rdandres@platonmartinez.com', rate: '', initials: 'RDA')
Lawyer.create(first_name: 'LUCKY ANGELO', last_name: 'ARANAS', middle_name: 'TEMPORAZA', position: 'JUNIOR ASSOCIATE', email: 'ltaranas@platonmartinez.com', rate: '', initials: 'LTA')
Lawyer.create(first_name: 'JOEY', last_name: 'ARCILLA', middle_name: 'S', position: '', email: '', rate: '', initials: 'JSA')
Lawyer.create(first_name: 'PRESCILA', last_name: 'BARTOLOME', middle_name: 'DY CHUA', position: '', email: '', rate: '', initials: 'PDCB')
Lawyer.create(first_name: 'JON', last_name: 'BELLO', middle_name: 'O', position: '', email: '', rate: '', initials: 'JOB')
Lawyer.create(first_name: 'JEROME', last_name: 'BONSOL', middle_name: 'C', position: '', email: '', rate: '', initials: 'JCB')
Lawyer.create(first_name: 'JOUSTINE FELIX', last_name: 'CAMPANA', middle_name: 'F', position: '', email: '', rate: '', initials: 'JFC')
Lawyer.create(first_name: 'MARIA JOSELLA TERESA', last_name: 'CARDENAS', middle_name: 'MADRONIO', position: 'JUNIOR ASSOCIATE', email: 'jtcardenas@platonmartinez.com', rate: '', initials: 'JTC')
Lawyer.create(first_name: 'PAUL CORNELIUS', last_name: 'CASTILLO', middle_name: 'TANJUSAY', position: 'JUNIOR ASSOCIATE', email: 'ptcastillo@platonmartinez.com', rate: '', initials: 'PTC')
Lawyer.create(first_name: 'AILEEN GRACE', last_name: 'CERO', middle_name: 'M', position: '', email: '', rate: '', initials: 'AGMC')
Lawyer.create(first_name: 'JOVIAN JUBERT', last_name: 'DUMLAO', middle_name: 'SANTOS', position: 'SENIOR ASSOCIATE', email: 'jsdumlao@platonmartinez.com', rate: '', initials: 'JSSD')
Lawyer.create(first_name: 'WARREN', last_name: 'DY CHUA', middle_name: 'Y', position: '', email: '', rate: '', initials: 'WYDC')
Lawyer.create(first_name: 'ISAGANI ELIAS', last_name: 'ELACIO', middle_name: 'A', position: '', email: '', rate: '', initials: 'IEAE')
Lawyer.create(first_name: 'FULGENCIO', last_name: 'FACTORAN', middle_name: 'M', position: '', email: '', rate: '', initials: 'FMF')
Lawyer.create(first_name: 'ISRAFEL', last_name: 'FAGELA', middle_name: 'DATU', position: 'JUNIOR PARTNER', email: 'idfagela@platonmartinez.com', rate: '', initials: 'IDF')
Lawyer.create(first_name: 'MARY JOYCE', last_name: 'FLORENDO', middle_name: 'G', position: '', email: '', rate: '', initials: 'MUGF')
Lawyer.create(first_name: 'ANNA JAZYVEN', last_name: 'GONGORA', middle_name: 'VALENZUELA', position: '', email: '', rate: '', initials: 'AJVG')
Lawyer.create(first_name: 'ANTHONY RAYMOND', last_name: 'GOQUINGCO', middle_name: 'A', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ERWIN', last_name: 'HERRERA', middle_name: 'SANTOS', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'JOAN CATHERINE', last_name: 'LIBAN', middle_name: 'R', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ELSON', last_name: 'MANAHAN', middle_name: 'BAUTISTA', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'CORNELIUS VICTOR', last_name: 'MARIANO', middle_name: 'L', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'MIA CARISSA', last_name: 'MARTIN', middle_name: 'CELESTIAL', position: 'JUNIOR PARTNER', email: 'mcmartin@platonmartinez.com', rate: '', initials: 'MCCM')
Lawyer.create(first_name: 'NARCISA', last_name: 'MEDINA', middle_name: 'TUMBAGAHON', position: 'JUNIOR ASSOCIATE', email: 'ntmedina@platonmartinez.com', rate: '', initials: 'NTM')
Lawyer.create(first_name: 'ETHEL', last_name: 'MERCADO', middle_name: 'V', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ARNALDO', last_name: 'MORALEJO', middle_name: 'C', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'PETER PAUL', last_name: 'NATIVIDAD', middle_name: 'TURINGAN', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'BRAN MATTHEW', last_name: 'NEPOMUCENO', middle_name: 'C', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'FAYE CHRISTINE', last_name: 'PAREDES', middle_name: 'M', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'DIONNE', last_name: 'PULMA', middle_name: 'ECAP', position: 'SENIOR ASSOCIATE', email: 'depulma@platonmartinez.com', rate: '', initials: 'DEP')
Lawyer.create(first_name: 'FELIX CONRAD', last_name: 'REYES', middle_name: 'BAES', position: 'JUNIOR ASSOCIATE', email: 'fbreyes@platonmartinez.com', rate: '', initials: 'FBR')
Lawyer.create(first_name: 'LILI-MAE', last_name: 'REYES', middle_name: 'TEE', position: 'JUNIOR ASSOCIATE', email: 'ltreyes@platonmartinez.com', rate: '', initials: 'LTR')
Lawyer.create(first_name: 'JOAN KAREN', last_name: 'RIOLA', middle_name: 'A', position: '', email: '', rate: '', initials: 'JKAR')
Lawyer.create(first_name: 'ALDWIN', last_name: 'SALUMBIDES', middle_name: 'B', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ENRICO', last_name: 'SANDOVAL', middle_name: 'B', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'JENNY', last_name: 'SANTIAGO', middle_name: 'ROBLES', position: 'JUNIOR PARTNER', email: 'jrsantiago@platonmartinez.com', rate: '', initials: 'JRS')
Lawyer.create(first_name: 'EDLYN MARGARET', last_name: 'SANTIAGO', middle_name: 'CORDERO', position: 'JUNIOR ASSOCIATE', email: 'ecsantiago@platonmartinez.com', rate: '', initials: 'ECS')
Lawyer.create(first_name: 'RACHELLE AILEEN', last_name: 'SANTOS', middle_name: 'SANTOS', position: 'JUNIOR PARTNER', email: 'rssantos@platonmartinez.com', rate: '', initials: 'RSS')
Lawyer.create(first_name: 'JASON KYLE', last_name: 'SARENAS', middle_name: 'MANGROBANG', position: 'JUNIOR ASSOCIATE', email: 'kmsarenas@platonmartinez.com', rate: '', initials: 'KMS')
Lawyer.create(first_name: 'PATRICIA', last_name: 'SEE', middle_name: 'G', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ARTURO', last_name: 'SELIM', middle_name: 'GARCIA', position: 'JUNIOR PARTNER', email: 'agselim@platonmartinez.com', rate: '', initials: 'AGS')
Lawyer.create(first_name: 'ALFONSO MIGUEL', last_name: 'SIASON', middle_name: 'MARQUEZ-LIM', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'JUFIL', last_name: 'SIQUIAN', middle_name: 'E', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'PORTIA SHIRLEY', last_name: 'VALENCIA', middle_name: 'V', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ENRIQUE UAN', last_name: 'VERA', middle_name: 'C', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ALPHEUS	TIAMSON', last_name: 'VILLALUZ', middle_name: 'TIAMSON', position: 'JUNIOR ASSOCIATE', email: 'atvillaluz@platonmartinez.com', rate: '', initials: 'ATV')
Lawyer.create(first_name: 'ARMIN NOEL', last_name: 'VILLAMONTE', middle_name: 'B', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'VIMARI', last_name: 'VILLAMOR', middle_name: 'DELGADO', position: '', email: '', rate: '', initials: 'VDV')
Lawyer.create(first_name: 'ANTHEA', last_name: 'VILLARUEL', middle_name: 'REYES', position: '', email: '', rate: '', initials: '')


FileMatter.create(file_code: '2001-021', client_id: 1, title: 'GENERAL FILE', case_number: '', case_date: '01/31/01')
FileMatter.create(file_code: '2001-028', client_id: 2, title: 'GENERAL FILE', case_number: '', case_date: '02/06/01')
FileMatter.create(file_code: '1997-163', client_id: 3, title: 'GENERAL FILE', case_number: '', case_date: '06/03/97')
FileMatter.create(file_code: '2005-077', client_id: 4, title: 'PEOPLE OF THE PHILIPPINES VERSUS FLORENTINO QUARTZ P. REQUINTA with LIGHT GREEN ENVELOP & TSN', case_number: 'I.S. # 03-3486, CRIM. CASE # 05-0105 with CA-G.R. SP # 89893, CA-G.R. SP # 102322', case_date: '04/20/05')
FileMatter.create(file_code: '1997-241', client_id: 5, title: 'JOINT VENTURE FOR WASTE DISPOSAL', case_number: '', case_date: '08/12/97')
FileMatter.create(file_code: '1999-282', client_id: 6, title: 'GENERAL FILE', case_number: '', case_date: '10/04/99')
FileMatter.create(file_code: '2005-191', client_id: 6, title: 'ABN AMRO BANK, INC. VERSUS MA. TERESITA A. GUINTO', case_number: 'CIVIL CASE # 05-863', case_date: '08/29/05')
FileMatter.create(file_code: '2005-249', client_id: 6, title: 'ABN AMRO BANK, INC. VERSUS FILOMENO G. YAPTINCHAY', case_number: 'CIVIL CASE # 05-1012', case_date: '10/28/05')
FileMatter.create(file_code: '2005-250', client_id: 6, title: 'ABN AMRO BANK, INC. VERSUS SHALIMAR L. BARZAGA with TSN', case_number: 'CIVIL CASE # 05-1015', case_date: '10/28/05')
FileMatter.create(file_code: '2005-251', client_id: 6, title: 'CLAIM AGAINST MS. ROSARIO F. TEVES', case_number: '', case_date: '10/28/05')
FileMatter.create(file_code: '2007-053', client_id: 6, title: 'ABN AMRO SAVINGS BANK CORPORATION (now ABN AMRO BANK, INC.) VERSUS COMMISSIONER OF INTERNAL REVENUE', case_number: 'CTA CASE # 7089, EN BANC # 446, G.R. # 190898', case_date: '03/28/07')
FileMatter.create(file_code: '2007-068', client_id: 6, title: 'MAKATI CITY BUSINESS TAX', case_number: '', case_date: '04/23/07')
FileMatter.create(file_code: '2007-076', client_id: 6, title: 'PRELIMINARY ASSESSMENT NOTICE ON 2002 & 2003 VAT & DST DEFICIENCIES', case_number: '', case_date: '05/03/07')
FileMatter.create(file_code: '2007-103', client_id: 6, title: 'ABN AMRO BANK, INC. VERSUS EDUARDO BANAAG, JR.', case_number: 'CIVIL CASE # 07-606, CA-G.R. CV # 95329', case_date: '07/09/07')
FileMatter.create(file_code: '2010-060', client_id: 6, title: 'BUREAU OF INTERNAL REVENUE VERSUS WINSTON L. PECKSON ET AL.', case_number: 'NPS # 10B-00529', case_date: '04/08/10')
FileMatter.create(file_code: '2010-195', client_id: 7, title: 'DUE DILIGENCE ON S & J INTERNATIONAL CORPORATION AND SHARE PURCHASE AGREEMENTS', case_number: '', case_date: '10/21/10')
FileMatter.create(file_code: '2005-297', client_id: 8, title: 'PURCHASE OF ROCKWELL CONDOMINIUM UNIT', case_number: '', case_date: '12/15/05')
FileMatter.create(file_code: '2007-108', client_id: 9, title: 'GENERAL FILE', case_number: '', case_date: '07/18/07')
FileMatter.create(file_code: '2008-037', client_id: 10, title: 'COMPLAINT AGAINST SPS. RENE & IRENE RONAK', case_number: '', case_date: '03/07/08')
FileMatter.create(file_code: '2001-278', client_id: 11, title: 'PHILIPPINE SAVINGS BANK VERSUS ACM LANDHOLDINGS', case_number: 'CIVIL CASE# 01-854', case_date: '10/29/01')
FileMatter.create(file_code: '2002-352', client_id: 11, title: 'PEOPLE OF THE PHILIPPINES VERSUS ATTY. YASMIN ANDAYA ET AL.', case_number: 'CRIM. CASE# 310543-48', case_date: '11/29/02')
FileMatter.create(file_code: '2009-189', client_id: 12, title: 'CHILD SUPPORT ENFORCEMENT', case_number: '', case_date: '12/18/09')
FileMatter.create(file_code: '1980-081', client_id: 13, title: 'GENERAL FILE (OLD FILES) INACTIVE FILE', case_number: '', case_date: '')
FileMatter.create(file_code: '1996-1028', client_id: 13, title: 'GENERAL FILE (EXISTING FILES)', case_number: '', case_date: '09/21/96')
FileMatter.create(file_code: '1996-1066', client_id: 13, title: 'BP 22 COMPLAINT AGAINST NICOS ENTERPRISES', case_number: 'I.S. # 963337', case_date: '10/11/96')
FileMatter.create(file_code: '1996-1067', client_id: 13, title: 'BP 22 COMPLAINT AGAINST DANPA MANUFACTURING', case_number: 'CIVIL CASE # 96336', case_date: '10/11/96')
FileMatter.create(file_code: '1996-1068', client_id: 13, title: 'BP 22 COMPLAINT AGAINST TML GARMENTS', case_number: '', case_date: '10/11/96')
FileMatter.create(file_code: '1996-1069', client_id: 13, title: 'COMPLAINT AGAINST LABELLE APPAREL CORPORATION', case_number: '', case_date: '10/11/96')
FileMatter.create(file_code: '1996-1070', client_id: 13, title: 'COMPLAINT AGAINST MINES WORLDWIDE', case_number: '', case_date: '10/11/96')
FileMatter.create(file_code: '1997-028', client_id: 13, title: 'PEOPLE OF THE PHILIPPINES VERSUS MACARIO NICOS, NICOS GARMENTS', case_number: 'CRIMINAL CASE # 212077', case_date: '01/17/97')
FileMatter.create(file_code: '1997-051', client_id: 13, title: 'ACOTEX PHILIPPINES, INC. VERSUS TML GARMENTS, INC.', case_number: '', case_date: '02/10/97')
FileMatter.create(file_code: '1997-091', client_id: 13, title: '3A-APPAREL', case_number: 'CIVIL CASE #97-897', case_date: '03/19/97')
FileMatter.create(file_code: '1998-127', client_id: 13, title: 'CLAIM OF AGAINST HAMMER GARMENTS', case_number: 'I.S. # 98-10816', case_date: '05/21/98')
FileMatter.create(file_code: '1998-296', client_id: 13, title: 'FINETEX GARMENTS MFG.,  OVERDUE ACCOUNT', case_number: '', case_date: '12/14/98')
FileMatter.create(file_code: '2000-142', client_id: 13, title: 'UNPAID ACCOUNT OF SQUARE GEM MANUFACTURING CORPORATION', case_number: '', case_date: '05/10/00')
FileMatter.create(file_code: '2000-143', client_id: 13, title: 'UNPAID ACCOUNT OIF LEL GARMENTS', case_number: '', case_date: '05/10/00')
FileMatter.create(file_code: '1998-001', client_id: 13, title: 'HANG SUNG INTERNATIONAL VERSUS ACOTEX INDUSTRIES CORPORATION', case_number: 'CIVIL CASE # 58878', case_date: '01/07/98')
FileMatter.create(file_code: '2001-092', client_id: 13, title: 'LILIAN IGNACIO', case_number: 'I.S.# 01-227', case_date: '04/24/01')
FileMatter.create(file_code: '2002-243', client_id: 13, title: 'NELSON CILLO VERSUS ACOTEX INDUSTRIES CORPORATION ET AL.', case_number: 'NLRC CASE# RAB IV-05-17402 03-L', case_date: '09/03/02')
FileMatter.create(file_code: '2002-332', client_id: 13, title: 'PLANT ACCIDENT-GIOVANNI BARTOLOME', case_number: '', case_date: '11/19/02')
FileMatter.create(file_code: '1996-1062', client_id: 14, title: 'GENERAL FILE', case_number: '', case_date: '10/06/96')
FileMatter.create(file_code: '1996-1014', client_id: 15, title: 'GENERAL FILE', case_number: '', case_date: '09/25/96')
FileMatter.create(file_code: '2000-013', client_id: 16, title: 'APPLICATION FOR REGISTRATION WITH THE INTELLECTUAL PROPERTY OFFICE', case_number: '', case_date: '01/11/00')
FileMatter.create(file_code: '2003-166', client_id: 16, title: 'LABOR DISPUTE AT ADAMSON & ADAMSON, INC.', case_number: 'NCMB-NCR-NS--06-180-03', case_date: '07/04/03')
FileMatter.create(file_code: '1997-125', client_id: 16, title: '1997 CBA NEGOTIATIONS', case_number: '', case_date: '04/17/97')
FileMatter.create(file_code: '1997-181', client_id: 16, title: 'NEGOTIATIONS FOR PURCHASE EQUIPMENTS', case_number: '', case_date: '06/20/97')
FileMatter.create(file_code: '1997-276', client_id: 16, title: 'INCORPORATION OF FOCUSED & STRATEGIC DISTRIBUTION INC. (FAST)', case_number: '', case_date: '09/11/97')
FileMatter.create(file_code: '1997-282', client_id: 16, title: 'ASSET MARKETING CORPORATION', case_number: '', case_date: '09/19/97')
FileMatter.create(file_code: '1997-289', client_id: 16, title: 'NOTICE OF STRIKE', case_number: 'NCMR-NCR-MS # 09-401-97', case_date: '12/12/97')
FileMatter.create(file_code: '1997-035', client_id: 16, title: 'GENERAL FILE', case_number: '', case_date: '01/27/97')
FileMatter.create(file_code: '1997-036', client_id: 16, title: 'LABOR FILE', case_number: '', case_date: '01/27/97')
FileMatter.create(file_code: '1998-185', client_id: 16, title: 'SYNDICATED LOAN', case_number: '', case_date: '08/04/98')
FileMatter.create(file_code: '1999-073', client_id: 16, title: 'PREVENTIVE MEDIATION', case_number: '', case_date: '03/19/99')
FileMatter.create(file_code: '2000-259', client_id: 16, title: '2000-2002 COLLECTIVE BARGAINING AGREEMENT', case_number: '', case_date: '09/12/00')
FileMatter.create(file_code: '2002-227', client_id: 16, title: 'COLLECTIVE BARGAINING AGREMENT', case_number: '', case_date: '08/26/02')
FileMatter.create(file_code: '2002-087', client_id: 16, title: 'ALDRIN EVANGELISTA VERSUS ADAMSON AND ADAMSON, INC.', case_number: 'NLRC NCR (SOUTH) CASE#30-01-00663-02', case_date: '03/22/02')
FileMatter.create(file_code: '2003-221', client_id: 16, title: 'MARTIN PATRICIO VERSUS ADAMSON & ADAMSON, INC.', case_number: 'NLRC CASE# RAB-IV-07-17862-03-L', case_date: '09/16/03')
FileMatter.create(file_code: '2003-063', client_id: 16, title: 'ADAMSON & ADAMSON EMPLOYEES UNION-FFW VERSUS ADAMSON & ADAMSON', case_number: 'NLRC NCR CASE# 00-01-00753-03', case_date: '03/13/03')
FileMatter.create(file_code: '2003-064', client_id: 16, title: 'DENNIS BONICILLO ET AL. VERSUS ADAMSON & ADAMSON, INC. ET AL.', case_number: 'NLRC NCR CASE# 03-17051-03-L', case_date: '03/13/03')
FileMatter.create(file_code: '2004-130', client_id: 17, title: 'SHARE OPTION AGREEMENT BETWEEN MANILA PROPERTIES, INC. & PHILNICO HOLDINGS, LTD.', case_number: '', case_date: '06/28/04')
FileMatter.create(file_code: '2008-098', client_id: 18, title: 'SALE OF PROPERTIES TO HAUSLAND DEVELOPMENT CORPORATION/WILFREDO TAN', case_number: '', case_date: '06/23/08')
FileMatter.create(file_code: '2008-171', client_id: 19, title: 'CONFLICT OF INTEREST SALE OF LAND TO THE TOLL REGULATORY BOARD with NOTES ON THE LAW, EXHIBITS FILE, NEWS CLIPPINGS', case_number: '', case_date: '09/30/08')
FileMatter.create(file_code: '2005-042', client_id: 20, title: 'PEOPLE OF THE PHILIPPINES VERSUS MARY ANN BEVERLY PARAS', case_number: 'I.S. # 04-016120', case_date: '03/05/05')
FileMatter.create(file_code: '1979-1111', client_id: 21, title: 'GENERAL FILE (OLD FILES) INACTIVE FILE', case_number: '', case_date: '')
FileMatter.create(file_code: '1981-950', client_id: 21, title: 'INSURANCE POLICIES', case_number: '', case_date: '08/24/81')
FileMatter.create(file_code: '1981-962', client_id: 21, title: 'CLAIM AGAINST PHILIPPINE UNDERWRITERS FINANCE CORPORATION', case_number: '', case_date: '08/27/81')
FileMatter.create(file_code: '1992-700', client_id: 21, title: 'FLOATING CHARGE TO BE EXECUTED IN FAVOUR OF BANK', case_number: '', case_date: '11/26/92')
FileMatter.create(file_code: '1994-421', client_id: 21, title: 'DUMAGUING VERSUS ADRISTE PHILIPPINES, INC.', case_number: '', case_date: '')
FileMatter.create(file_code: '1996-1031', client_id: 21, title: 'LABOR FILE', case_number: '', case_date: '09/14/96')
FileMatter.create(file_code: '1996-1056', client_id: 21, title: 'GENERAL FILE (EXISTING FILES)', case_number: '', case_date: '10/06/96')
FileMatter.create(file_code: '1996-1218', client_id: 21, title: 'RENATO DE VERA', case_number: '', case_date: '12/19/96')
FileMatter.create(file_code: '1997-221', client_id: 21, title: 'COMPLAINT INSPECTION OF ADRISTE PHILIPPINES, INC. (PEZA)', case_number: '9610-CI-20', case_date: '08/01/97')
FileMatter.create(file_code: '1997-237', client_id: 21, title: 'COMPUTER PROGRAM COMPLEX COMPUTER CENTER (GAWIDAN CASE )', case_number: 'CIVIL CASE # 3941-R', case_date: '08/11/97')
FileMatter.create(file_code: '1997-238', client_id: 21, title: 'REMEDIOS DOMECYAS VERSUS ADRISTE PHILIPPINES, INC.', case_number: 'NLRC NCR CASE # 07-0221-97', case_date: '08/11/97')
FileMatter.create(file_code: '1997-252', client_id: 21, title: 'MARIPAZ LIBAN', case_number: '', case_date: '08/28/97')
FileMatter.create(file_code: '1997-361', client_id: 21, title: 'CHRISTOPHER ALFARO VERSUS ADRISTE PHILIPPINES, INC.', case_number: 'NLRC NCR CASE # 09-0318-97', case_date: '11/17/97')
FileMatter.create(file_code: '1997-157-A', client_id: 21, title: 'MARLON GARGAR', case_number: '', case_date: '05/24/97')
FileMatter.create(file_code: '2001-137', client_id: 21, title: 'INCREASE OF CAPITAL STOCK TO 54, 825,000.00', case_number: '', case_date: '06/14/01')
FileMatter.create(file_code: '2005-102-A', client_id: 21, title: 'ELENA CAYANAN ET AL. VERSUS ADRISTE PHILIPPINES, INC. ET AL.', case_number: 'NLRC CASE # RAB-CAR-04-182-05', case_date: '05/23/05')
FileMatter.create(file_code: '2005-102-B', client_id: 21, title: 'EVANGELINE ESPIRITU VERSUS ADRISTE PHILIPPINES, INC.', case_number: 'NLRC CASE # RAB-CAR-04-182-05', case_date: '05/30/05')
FileMatter.create(file_code: '2005-102-C', client_id: 21, title: 'MELINDA LLOVERAS VERSUS ADRISTE PHILIPPINES, INC.', case_number: 'NLRC CASE # RAB-CAR-04-182-05', case_date: '05/30/05')
FileMatter.create(file_code: '2007-094', client_id: 21, title: 'REMY C. ORPILLA ET AL. VERSUS ADRISTE PHILIPPINES, INC. ET AL.', case_number: 'NLRC CASE # RAB-CAR-05-0220-07, CA-G.R. SP # 109509 WITH SUPREME COURT FILE', case_date: '06/18/07')
FileMatter.create(file_code: '2012-008', client_id: 22, title: 'JENNIFER M. PELESCO VERSUS ADVANCE RECOVERY SYSTEMS, INC. ET AL.', case_number: 'NLRC NCR CASE # 12-18401-11', case_date: '01/31/12')
FileMatter.create(file_code: '1998-059', client_id: 23, title: 'CONSUMER UNION OF THE PHILIPPINES VERSUS ADBOARD ET AL.', case_number: 'CIVIL CASE # 98-86914', case_date: '02/24/98')
FileMatter.create(file_code: '2001-279', client_id: 24, title: 'EXTRA-JUDICIAL PARTITION & SETTLEMENT OF ESTATE OF OSCAR AFRICA', case_number: '', case_date: '10/29/01')
FileMatter.create(file_code: '2005-299', client_id: 24, title: 'GENERAL FILE', case_number: '', case_date: '12/15/05')
FileMatter.create(file_code: '1995-037', client_id: 25, title: 'GENERAL FILE', case_number: '', case_date: '')
FileMatter.create(file_code: '1996-1060', client_id: 25, title: 'GENERAL FILE', case_number: '', case_date: '10/06/96')
FileMatter.create(file_code: '1991-069', client_id: 26, title: 'GENERAL FILE / CORPORATE FILE with AMENDED ARTICLES OF INCORPORATION & AMENDED BY-LAWS', case_number: '', case_date: '')
FileMatter.create(file_code: '2003-303', client_id: 27, title: 'GENERAL FILE  With ARTICLES OF INCORPORATION & BY - LAWS (photocopy only), MINUTES OF MEETING OF BOARD OF DIRECTORS & STOCKHOLDERS, WITH CORPORATE SECRETARYS CERTIFICATE FILE', case_number: '', case_date: '12/08/03')
FileMatter.create(file_code: '2010-210', client_id: 27, title: 'PURCHASE OF BATANGAS PROPERTY (CONTRACT TO SELL BETWEEN AGROTEX AND FIRST PHILIPPINE INDUSTRIAL BANK, INC.)', case_number: '', case_date: '11/17/10')
FileMatter.create(file_code: '2008-090', client_id: 28, title: 'GENERAL FILE', case_number: '', case_date: '06/04/08')
FileMatter.create(file_code: '1980-631', client_id: 29, title: 'LUMEN POLICARPIO VERSUS AIR FRANCE', case_number: '', case_date: '')
FileMatter.create(file_code: '1984-401', client_id: 29, title: 'MANUEL R. REGALLA VERSUS AIR FRANCE', case_number: '', case_date: '06/28/98')
FileMatter.create(file_code: '1985-573', client_id: 29, title: 'APPOINTMENT OF NEW RESIDENT AGENT', case_number: '', case_date: '10/04/85')
FileMatter.create(file_code: '1988-262', client_id: 29, title: 'MRS. LYDIA R. JASMINES', case_number: '', case_date: '04/26/88')
FileMatter.create(file_code: '1988-355', client_id: 29, title: 'JOKER ARROYO VERSUS AIR FRANCE', case_number: '', case_date: '')
FileMatter.create(file_code: '1990-404', client_id: 29, title: 'ABETO VERSUS AIR FRANCE', case_number: '', case_date: '')
FileMatter.create(file_code: '1990-460', client_id: 29, title: 'CLAIM OF MRS SEMADAR GOFFER & FAMILY', case_number: '', case_date: '07/17/90')
FileMatter.create(file_code: '1990-545', client_id: 29, title: 'CLAIM OF MR. & MRS. BENEDICTO LEDESMA & SONS', case_number: '', case_date: '08/26/90')
FileMatter.create(file_code: '1990-572', client_id: 29, title: 'BENEDICTO ARCINAS VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 93-18132', case_date: '33120')
FileMatter.create(file_code: '1991-681', client_id: 29, title: 'IMELDA ROTAQUIO VERSUS AIR FRANCE ET AL.', case_number: 'CIVIL CASE # 91-58635 with CA-G.R. SP# 63691', case_date: '')
FileMatter.create(file_code: '1992-663', client_id: 29, title: 'CLAIM OF SHAM DASWANI FOR LOST WALKING STICK', case_number: '', case_date: '11/04/92')
FileMatter.create(file_code: '1992-069', client_id: 29, title: 'DEMAND LETTER OF ART LAWRENCE DIAZ AMINAC', case_number: '', case_date: '02/04/92')
FileMatter.create(file_code: '1993-488', client_id: 29, title: 'BONIFACIO GILLEGO VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 93-2328 with CA-G.R. SP# 56587, G.R. # 165266', case_date: '')
FileMatter.create(file_code: '1993-534', client_id: 29, title: 'OUTSTANDING ACCOUNT OF PILLAR TRANSPORT CORPORATION', case_number: '', case_date: '08/03/93')
FileMatter.create(file_code: '1993-067', client_id: 29, title: 'VICENTE B. FOZ DENIED BOARDING', case_number: '', case_date: '34001')
FileMatter.create(file_code: '1994-473', client_id: 29, title: 'MRS. CONSOLACION QUERIMIT', case_number: '', case_date: '34523')
FileMatter.create(file_code: '1994-733', client_id: 29, title: 'CLAIM FOR DAMAGES TO STATION OFFICE AT NAIA', case_number: '', case_date: '10/22/94')
FileMatter.create(file_code: '1995-384', client_id: 29, title: 'DAN SHAHAM, 2ND SECRETARY EMBASSY OF ISRAEL', case_number: '', case_date: '34887')
FileMatter.create(file_code: '1995-461', client_id: 29, title: 'RESHIEL FASHION INTERNATIONAL CORPORATION', case_number: 'CIVIL CASE # 95-0183 with CA-G.R. SP # 64265, G.R. # 183588', case_date: '08/09/95')
FileMatter.create(file_code: '1995-481', client_id: 29, title: 'MRS. BIENVENIDA A. CABANGON ET AL.', case_number: '', case_date: '08/18/95')
FileMatter.create(file_code: '1995-625', client_id: 29, title: 'LUMEN POLICARPIO VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 95-23539', case_date: '10/13/95')
FileMatter.create(file_code: '1995-640', client_id: 29, title: 'ACCOUNT OF PILLAR TRANSPORT CORPORATION (BOUNCED CHECKS)', case_number: '', case_date: '10/18/95')
FileMatter.create(file_code: '1995-666', client_id: 29, title: 'CLAIM OF AMELIA ANN GORDON DE LOS REYES', case_number: '', case_date: '11/06/95')
FileMatter.create(file_code: '1996-229', client_id: 29, title: 'COL. ROLANDO ABADILLA', case_number: '', case_date: '35187')
FileMatter.create(file_code: '1996-1030', client_id: 29, title: 'APPLICATION FOR WINTER SCHEDULE OCTOBER 27, 1996', case_number: '', case_date: '09/14/96')
FileMatter.create(file_code: '1996-1095', client_id: 29, title: 'GENERAL FILE', case_number: '', case_date: '10/14/96')
FileMatter.create(file_code: '1996-1129', client_id: 29, title: 'BENJAMIN K. LIBORO ET AL. VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 96-1562', case_date: '10/29/96')
FileMatter.create(file_code: '1996-1171', client_id: 29, title: 'RENEWAL OF LEASE CONTRACT WITH MIA AUTHORITY', case_number: '', case_date: '10/28/96')
FileMatter.create(file_code: '1996-079', client_id: 29, title: 'PHILAM INSURANCE VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 34-96', case_date: '')
FileMatter.create(file_code: '1997-110', client_id: 29, title: 'CONTRACT WITH MIASCOR', case_number: '', case_date: '35528')
FileMatter.create(file_code: '1997-148', client_id: 29, title: 'REDUNDANCY CARGO', case_number: '', case_date: '05/15/97')
FileMatter.create(file_code: '1997-156', client_id: 29, title: 'CLAIM OF UNDERSECRETARY JOSEFINA LICHAUCO', case_number: '', case_date: '05/23/97')
FileMatter.create(file_code: '1997-162', client_id: 29, title: 'POSITION PAPER ON GROSS PHILIPPINES BILLING ETC. C/R 99-138', case_number: '', case_date: '06/02/97')
FileMatter.create(file_code: '1997-229', client_id: 29, title: 'PRE-TERMINATION OF LEASE CONTRACT WITH BANK OF THE PHILIPPINE ISLAND', case_number: '', case_date: '08/06/97')
FileMatter.create(file_code: '1997-253', client_id: 29, title: 'RELAIS SATELLITES', case_number: '', case_date: '08/28/97')
FileMatter.create(file_code: '1997-281', client_id: 29, title: 'CONTRACT OF CORNERSTONE BUILDERS, INC.', case_number: '', case_date: '09/18/97')
FileMatter.create(file_code: '1997-285', client_id: 29, title: 'AIR FRANCE WINTER SCHEDULE 28 OCTOBER 97 TO 28 MARCH 1998', case_number: '', case_date: '09/19/97')
FileMatter.create(file_code: '1997-287', client_id: 29, title: 'JET TRAVEL, INC.', case_number: '', case_date: '09/22/97')
FileMatter.create(file_code: '1997-287', client_id: 29, title: 'CLAIM AGAINST GRAND AIR', case_number: '', case_date: '10/02/97')
FileMatter.create(file_code: '1997-318', client_id: 29, title: 'CBA AGREEMENT OF AIR FRANCE & MAFEA', case_number: '', case_date: '10/13/97')
FileMatter.create(file_code: '1997-363', client_id: 29, title: 'CONTRACT BETWEEN ALMANDINE, GARNET & SORREL, INC.', case_number: '', case_date: '11/18/97')
FileMatter.create(file_code: '1997-400', client_id: 29, title: 'MS. ZETA F. FELICIANO', case_number: '', case_date: '12/22/97')
FileMatter.create(file_code: '1997-026', client_id: 29, title: 'PEOPLE OF THE PHILIPPINES VERSUS ERNESTO ROXAS Y. CELIS', case_number: '', case_date: '01/17/97')
FileMatter.create(file_code: '1997-040', client_id: 29, title: 'LEASE CONTRACT WITH BPI 7TH FLR. CENTURY BUILDING', case_number: '', case_date: '01/31/97')
FileMatter.create(file_code: '1997-063', client_id: 29, title: 'SUMMER APPLICATION SCHEDULE 30 MARCH 1997', case_number: '', case_date: '02/17/97')
FileMatter.create(file_code: '1997-064', client_id: 29, title: 'DAMAGES TI AIRLINE OFFICER 4/F AT NAIA', case_number: '', case_date: '02/18/97')
FileMatter.create(file_code: '1997-074', client_id: 29, title: 'PEOPLE OF THE PHILIPPINES VERSUS OFELIA TY ET. AL.', case_number: 'CRIMINAL CASE # 90-8945', case_date: '02/27/97')
FileMatter.create(file_code: '1998-123', client_id: 29, title: 'EUROPEAN CHAMBER OF COMMERCE PROPOSED FOR NEW BUSINESS', case_number: '', case_date: '05/18/98')
FileMatter.create(file_code: '1998-214', client_id: 29, title: 'APPROVAL OF WINTER SCHEDULE 10/25/98 TO 3/27/99', case_number: '', case_date: '08/31/98')
FileMatter.create(file_code: '1998-255', client_id: 29, title: 'ASIA CREATIVE TOURS', case_number: '', case_date: '10/26/98')
FileMatter.create(file_code: '1998-282', client_id: 29, title: 'PHILIPPINE LEISURE, INC. VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 98-90408', case_date: '12/03/98')
FileMatter.create(file_code: '1998-293', client_id: 29, title: 'CLAIM OF SINING KUMINTANG BATANGAS', case_number: '', case_date: '12/14/98')
FileMatter.create(file_code: '1998-045', client_id: 29, title: 'CLAIM OF MR. PABLO T. AGOBA', case_number: '', case_date: '02/10/98')
FileMatter.create(file_code: '1998-047', client_id: 29, title: 'APPLICATION FOR SUMMER SCHEDULE', case_number: '', case_date: '02/11/98')
FileMatter.create(file_code: '1998-053', client_id: 29, title: 'RETIREMENTS BENEFITS/LAY-OFF POLICY', case_number: '', case_date: '02/16/98')
FileMatter.create(file_code: '1998-064', client_id: 29, title: 'AIR FRANCE AD/WRITE UP IN MAGAZINE COMMUNITY MANILA', case_number: '', case_date: '03/03/98')
FileMatter.create(file_code: '1999-114', client_id: 29, title: 'MA. LOURDES REYES VERSUS ERLINDA ALARAS/ FOR VIOLATION OF PHIL PASSPORT', case_number: 'I.S. # 99-139', case_date: '05/01/99')
FileMatter.create(file_code: '1999-135', client_id: 29, title: 'CLAIM OF MR. & MRS MARIO ORETA', case_number: 'CIVIL CASE # 99-1373', case_date: '05/28/99')
FileMatter.create(file_code: '1999-136', client_id: 29, title: 'CONTRACT OF LEASE BETWEEN MIAA & AIR FRANCE', case_number: '', case_date: '05/28/99')
FileMatter.create(file_code: '1999-138', client_id: 29, title: 'POSITION PAPER ON GROSS PHILIPPINES BILLING ETC. C/R 97-162', case_number: '', case_date: '05/28/99')
FileMatter.create(file_code: '1999-140', client_id: 29, title: 'NBI-LOURDES REYES VERSUS MARIDEL REYES', case_number: 'I.S # 99151', case_date: '06/01/99')
FileMatter.create(file_code: '1999-156', client_id: 29, title: 'CLAIM OF MS FELIZA ANGELES', case_number: '', case_date: '06/16/99')
FileMatter.create(file_code: '1999-182', client_id: 29, title: 'ABUSE OF FIFTH FREEDOM PRIVILEGES', case_number: '', case_date: '07/05/99')
FileMatter.create(file_code: '1999-262', client_id: 29, title: 'WINTER SCHEDULE OCT 1999 TO MAR 25 2000', case_number: '', case_date: '09/14/99')
FileMatter.create(file_code: '1999-331', client_id: 29, title: 'MAFEA CBA PROPOSALS', case_number: '', case_date: '36493')
FileMatter.create(file_code: '1999-357', client_id: 29, title: 'APPLICATION FOR SUMMER SCHEDULE', case_number: '', case_date: '36516')
FileMatter.create(file_code: '1999-053', client_id: 29, title: 'APPROVAL OF SUMMER SCHEDULE', case_number: '', case_date: '36216')
FileMatter.create(file_code: '1999-069', client_id: 29, title: 'PROPOSAL FOR AIR FRANCE SPECIAL FARES FOR CAB', case_number: '', case_date: '36235')
FileMatter.create(file_code: '2000-101', client_id: 29, title: 'COMPLAINT OF MS. REGINA ALBERT', case_number: '', case_date: '36614')
FileMatter.create(file_code: '2000-103', client_id: 29, title: '3 SEAMEN PASSENGER CONSTELLATION TRAVEL', case_number: '', case_date: '36615')
FileMatter.create(file_code: '2000-126', client_id: 29, title: 'LEASE CONTRACT BET MIAA AND AIR FRANCE 1999-2000', case_number: '', case_date: '36644')
FileMatter.create(file_code: '2000-161', client_id: 29, title: 'CONTRACT OF AVIATION SECURITY SERVICES WITH PASSCOR', case_number: '', case_date: '36675')
FileMatter.create(file_code: '2000-184', client_id: 29, title: 'CHARLES ZANI CONSULTANTS OVERDUE ACCOUNT OF P1,738,180.00, with TSN FOLDER', case_number: 'CIVIL CASE# 00-1424, CA-G.R. CV # 87192, G. R. #  185856, ', case_date: '36703')
FileMatter.create(file_code: '2000-201', client_id: 29, title: 'COMPLAINT ON AIR AIRFRANCE  BAGGAGE DELAY (MARIBEL RODOLFO ET AL)', case_number: '', case_date: '36726')
FileMatter.create(file_code: '2000-202', client_id: 29, title: 'CLAIM OF ATTY. NORDY DIPLOMA', case_number: '', case_date: '36728')
FileMatter.create(file_code: '2000-228', client_id: 29, title: 'CLAIM OF DR. SOLER', case_number: '', case_date: '36755')
FileMatter.create(file_code: '2000-235', client_id: 29, title: 'PEOPLE OF THE PHILIPPINES VERSUS IMELDA MEJIA SEMANA', case_number: 'CRIM. CASE# 00-1056', case_date: '36759')
FileMatter.create(file_code: '2000-241', client_id: 29, title: 'NBI-LOURDES REYES VERSUS ELISA BARROS Y. LETARGO', case_number: 'I.S.# 2000-1102', case_date: '36762')
FileMatter.create(file_code: '2000-246', client_id: 29, title: 'APPLICATION FOR WINTER SCHEDULE EFFECTIVE 28 OCTOBER 2000 TO MARCH', case_number: 'CAB CASE# 19734', case_date: '36767')
FileMatter.create(file_code: '2000-312', client_id: 29, title: 'CLAIM OF MR. CHARLES AUGUSTE ZANI', case_number: '', case_date: '36843')
FileMatter.create(file_code: '2000-037', client_id: 29, title: 'BERNADETTE DE LEON FOOD POISONING ON FLIGHT 185 (HK-PARIS-ROUTE OCT 4, 99)', case_number: '', case_date: '36559')
FileMatter.create(file_code: '2000-053', client_id: 29, title: 'JUSTICE RICARDO FRANCISCO VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 68451', case_date: '36570')
FileMatter.create(file_code: '2001-115', client_id: 29, title: 'TWO AIR FRANCE CREW  MEMBERS', case_number: '', case_date: '37033')
FileMatter.create(file_code: '2001-141', client_id: 29, title: 'CHARLES AUGUSTE RAYMUND VERSUS SINGAPORE AIRLINES  ', case_number: 'CIVIL CASE# 01-832, with CA-G.R. SP# 74383 with TSN & EVIDENCE FILE for PLAINTIFF) CA-G.R. CV  94429, G.R. # 199767', case_date: '37058')
FileMatter.create(file_code: '2001-183', client_id: 29, title: 'CLAIM OF MS. JOCELYN ARAMBULO-SISON ET AL.', case_number: '', case_date: '37099')
FileMatter.create(file_code: '2001-190', client_id: 29, title: 'PEOPLE OF THE PHILIPPINES VERSUS MARIDEL REYES', case_number: 'CRIM CASE# 00-0381', case_date: '37103')
FileMatter.create(file_code: '2001-193', client_id: 29, title: 'BAGGAGE LOSS CLAIM OF MR. GERARD ABIERA', case_number: '', case_date: '37109')
FileMatter.create(file_code: '2001-211', client_id: 29, title: 'CLAIM OF MS. MARIA LOURDES RAUSA ET AL.', case_number: '', case_date: '37124')
FileMatter.create(file_code: '2001-247', client_id: 29, title: 'APPLICATION FOR WINTER SCHEDULE 28 OCT. 2001 TO 30 MARCH 2002', case_number: 'CAB CASE# 20830', case_date: '37148')
FileMatter.create(file_code: '2001-311', client_id: 29, title: 'CLAIM OF ROGELIO GO', case_number: '', case_date: '37231')
FileMatter.create(file_code: '2001-015', client_id: 29, title: 'FOREIGN AIR CARRIER PERMIT / with EXHIBITS FOLDER & TSN', case_number: 'CAB CASE # 24326 including TEPORARY OPERATING PERMIT, CAB CASE # 22148', case_date: '36914')
FileMatter.create(file_code: '2001-024', client_id: 29, title: 'APPLICATION FOR SUMMER SCHEDULE MARCH 26, 2001 TO OCT. 27, 2001', case_number: '', case_date: '36924')
FileMatter.create(file_code: '2001-037', client_id: 29, title: 'IN THE MATTER OF THE APPLICATION FOR SPECIAL FARES FOR THE PERIOD 3/26/2001 TO 6/2001', case_number: 'CAB CASE# 20210', case_date: '36942')
FileMatter.create(file_code: '2001-065', client_id: 29, title: 'MONICA GABRIELLE T. VELASQUEZ', case_number: '', case_date: '36969')
FileMatter.create(file_code: '2002-195', client_id: 29, title: 'JUDY VILLA ANGELES FLIGHT 192', case_number: '', case_date: '37449')
FileMatter.create(file_code: '2002-220', client_id: 29, title: 'SAMPAGUITA TRAVEL CORPORATION', case_number: '', case_date: '37481')
FileMatter.create(file_code: '2002-241', client_id: 29, title: 'LEASE CONTRACT WITH NAIA IPT 3', case_number: '', case_date: '37502')
FileMatter.create(file_code: '2002-253', client_id: 29, title: 'APPLICATION FOR WINTER SCHEDULE 2002-2003', case_number: 'CAB CASE# 22031', case_date: '37518')
FileMatter.create(file_code: '2002-254', client_id: 29, title: 'LICENSE TO DO BUSINESS', case_number: '', case_date: '37520')
FileMatter.create(file_code: '2002-268', client_id: 29, title: 'CLAIM OF MR. JUAN RAMOS TANJUATCO', case_number: '', case_date: '37531')
FileMatter.create(file_code: '2002-274', client_id: 29, title: 'RECOMMENDED CAB POLICY ON FUEL SURCHARGES IMPOSITION FOR INTERNATIONAL CARGO SHIPMENTS', case_number: '', case_date: '37533')
FileMatter.create(file_code: '2002-297', client_id: 29, title: 'CLAIM OF MR. & MRS. JOSE SANDEJAS', case_number: 'CIVIL CASE# 03-480', case_date: '37553')
FileMatter.create(file_code: '2002-333', client_id: 29, title: 'NBI-SI ARNOLD ALBARILLO VERSUS CLARISSA P. ROSARIO', case_number: 'I.S.# 2002-976', case_date: '37214')
FileMatter.create(file_code: '2002-344', client_id: 29, title: 'AIR FRANCE CARGO VERSUS CITIMOVERS', case_number: '', case_date: '37582')
FileMatter.create(file_code: '2002-042', client_id: 29, title: 'APPLICATION FOR SUMMER SCHEDULE EFFECTIVE 31 MARCH 2002 TO 26 OCTOBER 20002', case_number: '', case_date: '37308')
FileMatter.create(file_code: '2002-050', client_id: 29, title: 'CONTRACT OF DAVE DE JESUS', case_number: '', case_date: '37315')
FileMatter.create(file_code: '2002-062', client_id: 29, title: 'DENIED BOARDING DUE TO OVERBOOKING OF DR. & MRS. ISIDRO BENITEZ', case_number: '', case_date: '03/06/02')
FileMatter.create(file_code: '2002-089', client_id: 29, title: 'CLAIM OF MRS. MITOS BAUTISTA', case_number: '', case_date: '37340')
FileMatter.create(file_code: '2002-093', client_id: 29, title: 'CLAIM OF AMALIA STEVENS with TSN & TRIAL NOTES', case_number: 'CIVIL CASE # Q-04-53094', case_date: '04/03/02')
FileMatter.create(file_code: '2003-139', client_id: 29, title: 'EXTENSION OF PROMO FARES FOR TRAVELLING PAIRS', case_number: 'CAB CASE# 22239', case_date: '06/09/03')
FileMatter.create(file_code: '2003-144', client_id: 29, title: 'MSM CONTRACTING CORPORATION UNPAID ACCOUNTABILITIES', case_number: '', case_date: '06/10/03')
FileMatter.create(file_code: '2003-146', client_id: 29, title: 'NBI-MA. LOURDES  REYES VERSUS ANGELINA GUALTER DE LANDICHO Y BANAOG', case_number: 'I.S.# 2003-712', case_date: '06/12/03')
FileMatter.create(file_code: '2003-150', client_id: 29, title: 'MR. RICARDO CUERVA', case_number: '', case_date: '06/17/03')
FileMatter.create(file_code: '2003-186', client_id: 29, title: 'SPS. JUAN LUIS AND ASUNCION MARIA FAUSTMANN', case_number: 'CIVIL CASE# 03-1124', case_date: '07/29/03')
FileMatter.create(file_code: '2003-216', client_id: 29, title: 'PROMO  FARES FOR WINTER 2003/2004', case_number: '', case_date: '09/09/03')
FileMatter.create(file_code: '2003-218', client_id: 29, title: 'MR. DAVID DE JESUS', case_number: '', case_date: '09/10/03')
FileMatter.create(file_code: '2003-226', client_id: 29, title: 'APPLICATION FOR WINTER SCHEDULE 2003/2004', case_number: 'CAB CASE NO. 24117', case_date: '09/17/03')
FileMatter.create(file_code: '2003-263', client_id: 29, title: 'COMPLAINT OF MS. ALICE BAUN', case_number: '', case_date: '37923')
FileMatter.create(file_code: '2003-280', client_id: 29, title: 'MR. AND MRS. HENRY CANOY VERSUS AIR FRANCE', case_number: 'CIVIL CASE # 04-105, CA-G.R. CV # 85621', case_date: '37944')
FileMatter.create(file_code: '2003-031', client_id: 29, title: 'APPLICATION FOR SUMMER SCHEDULE EFFECTIVE 31 MARCH TO 25 OCTOBER 2003', case_number: 'CAB CASE# 22193', case_date: '02/04/03')
FileMatter.create(file_code: '2003-050', client_id: 29, title: 'PROMO FARES', case_number: '', case_date: '03/04/03')
FileMatter.create(file_code: '2003-055', client_id: 29, title: 'MR. RALPH LIM JOSEPH', case_number: '', case_date: '03/06/03')
FileMatter.create(file_code: '2003-070', client_id: 29, title: 'MONDIAL-AMEXCO CREDIT CARD TRANSACTION', case_number: '', case_date: '03/20/03')
FileMatter.create(file_code: '2004-106', client_id: 29, title: 'COMPLAINT OF ATTY. & MRS. EFIPANIO MA. J. TERBIO', case_number: '', case_date: '04/26/04')
FileMatter.create(file_code: '2004-149', client_id: 29, title: 'JOSE Y. SONZA VERSUS AIR FRANCE & VINCENT RUAIS', case_number: 'CA-G.R. CV # 55126 / with  RTC-FOLDER CIVIL CASE #Q-89-3101 ORIGINAL FOLDER CONTAINING 6 FOLDER(GREEN COLOR FOLDER) INCL. TSN & CA FOLDER, G.R. # 167229', case_date: '04/20/04')
FileMatter.create(file_code: '2004-239', client_id: 29, title: 'MR. MARGARITO G. KISH', case_number: '', case_date: '11/04/04')
FileMatter.create(file_code: '2004-240', client_id: 29, title: 'MS. CATHERINE FITZSIMMONS VERSUS AIR FRANCE (PHILIPPINES)', case_number: 'CIVIL CASE # 87071', case_date: '11/04/04')
FileMatter.create(file_code: '2004-035', client_id: 29, title: 'APPLICATION FOR SUMMER SCHEDULE EFFECTIVE 28 MARCH 2004 UNTIL 29 OCT. 2004', case_number: 'CAB CASE # 24536', case_date: '02/16/04')
FileMatter.create(file_code: '2004-042', client_id: 29, title: 'IN THE MATTER OF THE APPLICATION FOR APPROVAL OF PROMO FARES FOR SUMMER 2004', case_number: 'CAB CASE # 24574', case_date: '03/02/04')
FileMatter.create(file_code: '2004-049', client_id: 29, title: 'MR. & MRS. HERNAN ILAGAN', case_number: '', case_date: '03/08/04')
FileMatter.create(file_code: '2004-082', client_id: 29, title: 'NBI-LOURDES REYES VERSUS WINIFREDA MONTECILLO', case_number: 'I.S.# 2003-1631', case_date: '04/20/04')
FileMatter.create(file_code: '1999-198', client_id: 29, title: 'AGREEMENT COVERING GOLD EXCLUSIVE PROGRAM', case_number: '', case_date: '07/16/99')
FileMatter.create(file_code: '2005-036', client_id: 29, title: 'REPUBLIC OF THE PHILIPPINES VERSUS CARLOS F.GARCIA ET AL.', case_number: 'CIVIL CASE # 0193', case_date: '03/07/05')
FileMatter.create(file_code: '2005-058', client_id: 29, title: 'JOHN ANTHONY DE CAMILLIS VERSUS AIR FRANCE PHILIPPINES/KLM AIR FRANCE with TSN', case_number: 'CIVIL CASE # 05-220, CA-G.R. CV # 90151', case_date: '04/01/05')
FileMatter.create(file_code: '2007-047', client_id: 29, title: 'CLAIM OF MR. ANTONIO JOSE ROXAS', case_number: '', case_date: '03/20/07')
FileMatter.create(file_code: '2009-006', client_id: 29, title: 'CLAIM OF DR. WILLIE GO', case_number: '', case_date: '01/19/09')
FileMatter.create(file_code: '2009-031', client_id: 29, title: 'WITHDRAWAL OF LICENSE TO OPERATE', case_number: '', case_date: '03/02/09')
FileMatter.create(file_code: '2009-079', client_id: 29, title: 'AF 447, JUNE 1, 2009 (JUGUETA)', case_number: '', case_date: '06/09/09')
FileMatter.create(file_code: '2012-022', client_id: 29, title: 'SPS. ATTY. RAUL GONZALEZ, SR. AND DRA. PACITA T. GONZALEZ VERSUS ALITALIA COMPANIA AERE ITALIANA AND AIR FRANCE KLM', case_number: 'CIVIL CASE # 73340', case_date: '03/07/12')
FileMatter.create(file_code: '2003-049', client_id: 30, title: 'GENERAL FILE', case_number: '', case_date: '03/03/03')
FileMatter.create(file_code: '2010-086', client_id: 31, title: 'GENERAL FILE', case_number: '', case_date: '06/09/10')
FileMatter.create(file_code: '2010-087', client_id: 31, title: 'LABOR DISPUTE (PETITION FOR ASSUMPTION OF JURISDICTION)', case_number: 'NCMB-RBXI-NS-05-004-10, NLRC RAB XI-10-00989-10, NLRC CASE # MC-06-000034-2010', case_date: '06/09/10')
FileMatter.create(file_code: '2010-110', client_id: 32, title: 'PURCHASE OF A CONDOMINIUM UNIT FROM SERENDRA, INC.', case_number: '', case_date: '07/05/10')
FileMatter.create(file_code: '2008-086', client_id: 33, title: 'COMPLAINT AGAINST MR. LUIS L. GARCIA', case_number: '', case_date: '05/30/08')
FileMatter.create(file_code: '2008-087', client_id: 33, title: 'COMPLAINT AGAINST ATTY. FERNANDO T. BARICAN', case_number: '', case_date: '05/30/08')
FileMatter.create(file_code: '2002-255', client_id: 34, title: 'PEOPLE OF THE PHILIPPINES VERSUS KISSENGER KRAFT Y BRION', case_number: 'CRIM. CASE# 9792-02-C', case_date: '09/21/02')

