# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Client.create(name: 'A LITTLE MONEY PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'A LITTLE WORLD', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AB GEVECO SIGURD WALLDALL', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABAT, ZENAIDA C. MRS.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABCC ENVIRONMENTAL TECHNOLOGIES', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABN AMRO  BANK, INC.  (NOW ROYAL BANK OF SCOTLAND)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABOITIZ, LUIS MIGUEL MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABOITIZ, MA. REGINA AFRICA', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ABRAC RESOURCES CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACACIO, ALBERT, MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACM LAND HOLDINGS, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACOSTA, ROWELA C. (REFERRED BY U.S. EMBASSY)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACOTEX INDUSTRIES CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACTIVE GROUP, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ACTIVE REALTY  & DEVELOPMENT CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADAMSON AND ADAMSON INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADAMS, MICHAEL MR. (MAA CONSULTANTS, INC.)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADANIEL, EPPIE', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADELFA PROPERTIES & SENATE PRESIDENT MANUEL B. VILLAR', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADIDAS PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADRISTE PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADVANCE RECOVERY SYSTEM, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ADVERTISING BOARD OF THE PHILIPPINES', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AFRICA, ROSARIO MRS.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AGHITECH PHILIPPINES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AGRI-REALTY COMPANY., INC. (FORMERLY PURIPHIL REALTY DEVELOPMENT, INC.)', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AGROTEX COMMODITIES, INC.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AIG AVIATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AIR FRANCE', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AIR FRANCE CARGO', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AJMR PORT SERVICES CORPORATION', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'AL AWAN SAMEER MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ALANANO, ARNNIE MR', email: '', contact_number: '', position: '', address: '', contact_person: '')
Client.create(name: 'ALBA, MARK MR.', email: '', contact_number: '', position: '', address: '', contact_person: '')


Lawyer.create(first_name: 'JOSE', last_name: 'FLORES', middle_name: 'PACIS', position: 'PARTNER', email: 'jpflores@platonmartinez.com', rate: '', initials: 'JPF')
Lawyer.create(first_name: 'SAKLOLO', last_name: 'LEANO', middle_name: 'ALLOGUINES', position: 'PARTNER', email: 'saleano@platonmartinez.com', rate: '', initials: 'SAL')
Lawyer.create(first_name: 'AUGUSTO', last_name: 'SAN PEDRO', middle_name: 'SANTOS', position: 'PARTNER', email: 'asanpedro@platonmartinez.com', rate: '', initials: 'ASP')
Lawyer.create(first_name: 'CARLOS', last_name: 'PLATON', middle_name: 'GUTIERREZ', position: 'PARTNER', email: 'cgplaton@platonmartinez.com', rate: '', initials: 'CGP')
Lawyer.create(first_name: 'HECTOR', last_name: 'MARTINEZ', middle_name: 'AGUILA', position: 'PARTNER', email: 'hamartinez@platonmartinez.com', rate: '', initials: 'HAM')
Lawyer.create(first_name: 'ENNESTINE', last_name: 'FERNANDO', middle_name: 'VILLAREAL', position: 'PARTNER', email: 'edvfernando@platonmartinez.com', rate: '', initials: 'EDVF')
Lawyer.create(first_name: 'GRACE', last_name: 'PANAGSAGAN', middle_name: 'PADILLA', position: 'PARTNER', email: 'gpqpanagsagan@platonmartinez.com', rate: '', initials: 'GPQP')
Lawyer.create(first_name: 'OVALITO PETER', last_name: 'BANTILAN', middle_name: 'MANDAC', position: 'PARTNER', email: 'pmbantilan@platonmartinez.com', rate: '', initials: 'PMB')
Lawyer.create(first_name: 'ANTHONY BRETT', last_name: 'ABENIR', middle_name: 'MANDE', position: 'JUNIOR PARTNER', email: 'abmabenir@platonmartinez.com', rate: '', initials: 'ABMA')
Lawyer.create(first_name: 'JORGE AMBROSIO', last_name: 'ABES', middle_name: 'P', position: '', email: '', rate: '', initials: 'JAPA')
Lawyer.create(first_name: 'RYAN', last_name: 'ANDRES', middle_name: 'DEL PRADO', position: 'JUNIOR ASSOCIATE', email: 'rdandres@platonmartinez.com', rate: '', initials: 'RDA')
Lawyer.create(first_name: 'LUCKY ANGELO', last_name: 'ARANAS', middle_name: 'TEMPORAZA', position: 'JUNIOR ASSOCIATE', email: 'ltaranas@platonmartinez.com', rate: '', initials: 'LTA')
Lawyer.create(first_name: 'JOEY', last_name: 'ARCILLA', middle_name: 'S', position: '', email: '', rate: '', initials: 'JSA')
Lawyer.create(first_name: 'PRESCILA', last_name: 'BARTOLOME', middle_name: 'DY CHUA', position: '', email: '', rate: '', initials: 'PDCB')
Lawyer.create(first_name: 'JON', last_name: 'BELLO', middle_name: 'O', position: '', email: '', rate: '', initials: 'JOB')
Lawyer.create(first_name: 'JEROME', last_name: 'BONSOL', middle_name: 'C', position: '', email: '', rate: '', initials: 'JCB')
Lawyer.create(first_name: 'JOUSTINE FELIX', last_name: 'CAMPANA', middle_name: 'F', position: '', email: '', rate: '', initials: 'JFC')
Lawyer.create(first_name: 'MARIA JOSELLA TERESA', last_name: 'CARDENAS', middle_name: 'MADRONIO', position: 'JUNIOR ASSOCIATE', email: 'jtcardenas@platonmartinez.com', rate: '', initials: 'JTC')
Lawyer.create(first_name: 'PAUL CORNELIUS', last_name: 'CASTILLO', middle_name: 'TANJUSAY', position: 'JUNIOR ASSOCIATE', email: 'ptcastillo@platonmartinez.com', rate: '', initials: 'PTC')
Lawyer.create(first_name: 'AILEEN GRACE', last_name: 'CERO', middle_name: 'M', position: '', email: '', rate: '', initials: 'AGMC')
Lawyer.create(first_name: 'JOVIAN JUBERT', last_name: 'DUMLAO', middle_name: 'SANTOS', position: 'SENIOR ASSOCIATE', email: 'jsdumlao@platonmartinez.com', rate: '', initials: 'JSSD')
Lawyer.create(first_name: 'WARREN', last_name: 'DY CHUA', middle_name: 'Y', position: '', email: '', rate: '', initials: 'WYDC')
Lawyer.create(first_name: 'ISAGANI ELIAS', last_name: 'ELACIO', middle_name: 'A', position: '', email: '', rate: '', initials: 'IEAE')
Lawyer.create(first_name: 'FULGENCIO', last_name: 'FACTORAN', middle_name: 'M', position: '', email: '', rate: '', initials: 'FMF')
Lawyer.create(first_name: 'ISRAFEL', last_name: 'FAGELA', middle_name: 'DATU', position: 'JUNIOR PARTNER', email: 'idfagela@platonmartinez.com', rate: '', initials: 'IDF')
Lawyer.create(first_name: 'MARY JOYCE', last_name: 'FLORENDO', middle_name: 'G', position: '', email: '', rate: '', initials: 'MUGF')
Lawyer.create(first_name: 'ANNA JAZYVEN', last_name: 'GONGORA', middle_name: 'VALENZUELA', position: '', email: '', rate: '', initials: 'AJVG')
Lawyer.create(first_name: 'ANTHONY RAYMOND', last_name: 'GOQUINGCO', middle_name: 'A', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ERWIN', last_name: 'HERRERA', middle_name: 'SANTOS', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'JOAN CATHERINE', last_name: 'LIBAN', middle_name: 'R', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ELSON', last_name: 'MANAHAN', middle_name: 'BAUTISTA', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'CORNELIUS VICTOR', last_name: 'MARIANO', middle_name: 'L', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'MIA CARISSA', last_name: 'MARTIN', middle_name: 'CELESTIAL', position: 'JUNIOR PARTNER', email: 'mcmartin@platonmartinez.com', rate: '', initials: 'MCCM')
Lawyer.create(first_name: 'NARCISA', last_name: 'MEDINA', middle_name: 'TUMBAGAHON', position: 'JUNIOR ASSOCIATE', email: 'ntmedina@platonmartinez.com', rate: '', initials: 'NTM')
Lawyer.create(first_name: 'ETHEL', last_name: 'MERCADO', middle_name: 'V', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ARNALDO', last_name: 'MORALEJO', middle_name: 'C', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'PETER PAUL', last_name: 'NATIVIDAD', middle_name: 'TURINGAN', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'BRAN MATTHEW', last_name: 'NEPOMUCENO', middle_name: 'C', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'FAYE CHRISTINE', last_name: 'PAREDES', middle_name: 'M', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'DIONNE', last_name: 'PULMA', middle_name: 'ECAP', position: 'SENIOR ASSOCIATE', email: 'depulma@platonmartinez.com', rate: '', initials: 'DEP')
Lawyer.create(first_name: 'FELIX CONRAD', last_name: 'REYES', middle_name: 'BAES', position: 'JUNIOR ASSOCIATE', email: 'fbreyes@platonmartinez.com', rate: '', initials: 'FBR')
Lawyer.create(first_name: 'LILI-MAE', last_name: 'REYES', middle_name: 'TEE', position: 'JUNIOR ASSOCIATE', email: 'ltreyes@platonmartinez.com', rate: '', initials: 'LTR')
Lawyer.create(first_name: 'JOAN KAREN', last_name: 'RIOLA', middle_name: 'A', position: '', email: '', rate: '', initials: 'JKAR')
Lawyer.create(first_name: 'ALDWIN', last_name: 'SALUMBIDES', middle_name: 'B', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ENRICO', last_name: 'SANDOVAL', middle_name: 'B', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'JENNY', last_name: 'SANTIAGO', middle_name: 'ROBLES', position: 'JUNIOR PARTNER', email: 'jrsantiago@platonmartinez.com', rate: '', initials: 'JRS')
Lawyer.create(first_name: 'EDLYN MARGARET', last_name: 'SANTIAGO', middle_name: 'CORDERO', position: 'JUNIOR ASSOCIATE', email: 'ecsantiago@platonmartinez.com', rate: '', initials: 'ECS')
Lawyer.create(first_name: 'RACHELLE AILEEN', last_name: 'SANTOS', middle_name: 'SANTOS', position: 'JUNIOR PARTNER', email: 'rssantos@platonmartinez.com', rate: '', initials: 'RSS')
Lawyer.create(first_name: 'JASON KYLE', last_name: 'SARENAS', middle_name: 'MANGROBANG', position: 'JUNIOR ASSOCIATE', email: 'kmsarenas@platonmartinez.com', rate: '', initials: 'KMS')
Lawyer.create(first_name: 'PATRICIA', last_name: 'SEE', middle_name: 'G', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ARTURO', last_name: 'SELIM', middle_name: 'GARCIA', position: 'JUNIOR PARTNER', email: 'agselim@platonmartinez.com', rate: '', initials: 'AGS')
Lawyer.create(first_name: 'ALFONSO MIGUEL', last_name: 'SIASON', middle_name: 'MARQUEZ-LIM', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'JUFIL', last_name: 'SIQUIAN', middle_name: 'E', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'PORTIA SHIRLEY', last_name: 'VALENCIA', middle_name: 'V', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ENRIQUE UAN', last_name: 'VERA', middle_name: 'C', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'ALPHEUS	TIAMSON', last_name: 'VILLALUZ', middle_name: 'TIAMSON', position: 'JUNIOR ASSOCIATE', email: 'atvillaluz@platonmartinez.com', rate: '', initials: 'ATV')
Lawyer.create(first_name: 'ARMIN NOEL', last_name: 'VILLAMONTE', middle_name: 'B', position: '', email: '', rate: '', initials: '')
Lawyer.create(first_name: 'VIMARI', last_name: 'VILLAMOR', middle_name: 'DELGADO', position: '', email: '', rate: '', initials: 'VDV')
Lawyer.create(first_name: 'ANTHEA', last_name: 'VILLARUEL', middle_name: 'REYES', position: '', email: '', rate: '', initials: '')


